/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjektRouteImport } from './routes/projekt'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TjansterSlugRouteImport } from './routes/tjanster.$slug'

const ProjektRoute = ProjektRouteImport.update({
  id: '/projekt',
  path: '/projekt',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TjansterSlugRoute = TjansterSlugRouteImport.update({
  id: '/tjanster/$slug',
  path: '/tjanster/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/projekt': typeof ProjektRoute
  '/tjanster/$slug': typeof TjansterSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/projekt': typeof ProjektRoute
  '/tjanster/$slug': typeof TjansterSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/projekt': typeof ProjektRoute
  '/tjanster/$slug': typeof TjansterSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kontakt' | '/projekt' | '/tjanster/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontakt' | '/projekt' | '/tjanster/$slug'
  id: '__root__' | '/' | '/kontakt' | '/projekt' | '/tjanster/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  ProjektRoute: typeof ProjektRoute
  TjansterSlugRoute: typeof TjansterSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projekt': {
      id: '/projekt'
      path: '/projekt'
      fullPath: '/projekt'
      preLoaderRoute: typeof ProjektRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tjanster/$slug': {
      id: '/tjanster/$slug'
      path: '/tjanster/$slug'
      fullPath: '/tjanster/$slug'
      preLoaderRoute: typeof TjansterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  ProjektRoute: ProjektRoute,
  TjansterSlugRoute: TjansterSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
